"""Validate, search and rebuild the versioned research source catalog (stdlib only)."""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import re
import sys
import unicodedata
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
REVIEW = ROOT / "docs/research/deep-review-2026-09-21"
DEPTHS = {"abstract", "selected_sections", "full_text"}
DECISIONS = {"adopt_candidate", "ablate_candidate", "defer", "reject_for_now"}


def work_key(record: dict) -> str:
    """Group versions of arXiv works; otherwise normalize the full title."""
    url = record["url"]
    match = re.search(r"arxiv.org/(?:abs|pdf|html)/(\d{4}\.\d{4,5})", url)
    if match:
        return "arxiv:" + match.group(1)
    title = unicodedata.normalize("NFKD", record["title"]).casefold()
    return re.sub(r"[^a-z0-9]", "", title)


def load_records(directory: Path = REVIEW) -> list[dict]:
    records = []
    seen = set()
    paths = sorted(directory.glob("*.sources.json"))
    if not paths:
        raise ValueError(f"No source ledgers in {directory}")
    for path in paths:
        items = json.loads(path.read_text())
        if not isinstance(items, list):
            raise ValueError(f"{path.name}: expected array")
        for item in items:
            ident = item.get("id", "")
            if not re.fullmatch(r"[ADMT]\d{2}", ident) or ident in seen:
                raise ValueError(f"{path.name}: invalid/duplicate ID {ident}")
            seen.add(ident)
            for key in ("title", "source_type", "voynich_implication"):
                if not isinstance(item.get(key), str) or not item[key].strip():
                    raise ValueError(f"{ident}: missing {key}")
            for key in ("authors", "sections_read", "supported_claims", "limitations"):
                values = item.get(key)
                if not isinstance(values, list) or not values or any(
                    not isinstance(v, str) or not v.strip() for v in values
                ):
                    raise ValueError(f"{ident}: invalid {key}")
            year = item.get("year")
            if year is not None and (type(year) is not int or not 1800 <= year <= 2026):
                raise ValueError(f"{ident}: invalid year")
            if item.get("version_date") is not None and not isinstance(item["version_date"], str):
                raise ValueError(f"{ident}: invalid version date")
            if item.get("read_depth") not in DEPTHS or item.get("decision") not in DECISIONS:
                raise ValueError(f"{ident}: invalid depth/decision")
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", item.get("accessed_date", "")):
                raise ValueError(f"{ident}: invalid access date")
            parsed = urlparse(item.get("url", ""))
            if parsed.scheme != "https" or not parsed.netloc:
                raise ValueError(f"{ident}: invalid primary URL")
            if "artifact_sha256" in item and not re.fullmatch(r"[0-9a-f]{64}", item["artifact_sha256"]):
                raise ValueError(f"{ident}: invalid artifact checksum")
            records.append({**item, "_ledger": path.name})
    return sorted(records, key=lambda r: r["id"])


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(records: list[dict]) -> str:
    counts = Counter(r["read_depth"] for r in records)
    groups: dict[str, list[str]] = {}
    for record in records:
        groups.setdefault(work_key(record), []).append(record["id"])
    duplicate = ["/".join(ids) for ids in groups.values() if len(ids) > 1]
    lines = [
        "# Searchable research source catalog",
        "",
        "Generated by `python3 scripts/research_catalog.py --write` from the four source ledgers.",
        "Review date: 2026-09-21. Read [the synthesis](README.md) before treating a source as a design recommendation.",
        "",
        f"**{len(records)} records; {len(groups)} distinct works/resources.** "
        f"Reading records: {counts['selected_sections']} selected sections/documentation, "
        f"{counts['abstract']} abstract-only, {counts['full_text']} full text "
        "(one short research note, not a full-length paper).",
        "",
        "Repeated work across disciplines: " + (", ".join(duplicate) or "none") + ". "
        "Counts describe this review, not the total literature, independent replications, or fully read papers.",
        "Version dates may name a preprint or release rather than the publication year. "
        "Unresolved date conflicts are retained in source limitations.",
        "",
        "Search examples (from the repository root):",
        "",
        "```sh",
        "python3 scripts/research_catalog.py --query 'key' --depth selected_sections",
        "python3 scripts/research_catalog.py --decision adopt_candidate",
        "python3 scripts/research_catalog.py --check",
        "```",
        "",
        "Each JSON record contains authors, exact URL, date/version, reading sections, supported claims, "
        "limitations, project implication and decision. Search includes these fields, not just titles. "
        "The ledgers are authoritative; this table is a rebuildable index.",
        "",
        "| ID | Work / primary source | Year | Reading depth | Decision | Ledger |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in records:
        lines.append(
            f"| {r['id']} | [{cell(r['title'])}]({r['url']}) | {r['year'] or 'undated'} | "
            f"{r['read_depth']} | {r['decision']} | [{r['_ledger']}]({r['_ledger']}) |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--write", action="store_true", help="Rebuild CATALOG.md")
    actions.add_argument("--check", action="store_true", help="Validate ledgers and catalog freshness")
    parser.add_argument("--query", default="", help="Case-insensitive substring across all source fields")
    parser.add_argument("--depth", choices=sorted(DEPTHS))
    parser.add_argument("--decision", choices=sorted(DECISIONS))
    args = parser.parse_args()
    records = load_records()
    catalog = REVIEW / "CATALOG.md"
    expected = render(records)
    if args.write:
        catalog.write_text(expected)
        print(f"Wrote {catalog.relative_to(ROOT)}")
    elif args.check:
        if not catalog.exists() or catalog.read_text() != expected:
            raise ValueError("Catalog is missing or stale; run --write")
        print(f"Validated {len(records)} records, {len({work_key(r) for r in records})} distinct works/resources")
    else:
        selected = [
            r for r in records
            if (not args.depth or r["read_depth"] == args.depth)
            and (not args.decision or r["decision"] == args.decision)
            and args.query.casefold() in json.dumps(r, ensure_ascii=False).casefold()
        ]
        for r in selected:
            print(f"{r['id']} | {r['title']} | {r['read_depth']} | {r['decision']}")
            print(f"  {r['url']}\n  {r['voynich_implication']}")
        print(f"{len(selected)} matching records")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ValueError, OSError, KeyError, TypeError) as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        sys.exit(1)
